version: '3.8'

services:
  ocr:
    image: alexxyk/surya-ocr:latest
    container_name: surya-ocr
    ports:
      - "5000:5000"  # API + Dashboard (all in one!)
    environment:
      # === Vision Configuration ===
      - VISION_PROVIDER=ollama
      - VISION_MODEL=qwen2.5vl:7b
      
      # === Ollama (only if VISION_PROVIDER=ollama) ===
      - OLLAMA_HOST=http://192.168.0.153:11434
      
      # === API Keys (only add the one you're using) ===
      - GEMINI_API_KEY=
      # - OPENAI_API_KEY=
      # - ANTHROPIC_API_KEY=
      
      # === OCR Settings ===
      - USE_HYBRID_OCR=true
      - PERFECT_TABLES=false
      
      # === Logging ===
      - LOG_LEVEL=INFO
    
    volumes:
      - surya-data:/app/data
      - surya-logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    networks:
      - surya-network

networks:
  surya-network:
    driver: bridge

volumes:
  surya-data:
  surya-logs:
